name: Test
on: ["push", "pull_request"]

jobs:
    sayhi:
        runs-on: ubuntu-latest
        steps:
            - run: "echo 'Running tests for ${{ github.repository }}'"
            - run: "echo 'Repo: ${{ github.repository }}'"
            - run: "echo 'Branch: ${{ github.ref }}'"
    code-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Set up Python 3.13
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13
            - name: Install pixi
              uses: prefix-dev/setup-pixi@v0.9.3
              with:
                  pixi-version: v0.62.2
            - name: Run code check
<<<<<<< HEAD
<<<<<<< HEAD
              run: |
                  pixi add ruff
                  pixi run ruff check
=======
              run: pixi run ruff check
>>>>>>> d356477 (add github workflow)
=======
              run: |
                  pixi add ruff
                  pixi run ruff check
>>>>>>> e61c314 (add ruff)
    test:
        runs-on: ubuntu-latest
        needs: code-check
        steps:
            - uses: actions/checkout@v6
            - name: Set up Python 3.13
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13
            - name: Install pixi
              uses: prefix-dev/setup-pixi@v0.9.3
              with:
                  pixi-version: v0.62.2
            - name: Run tests
              run: pixi run pytest
